image-upload
coleam00/bolt.new-any-llm pull request #332
Opened 2024-11-19 01:13 UTC by atrokhym

![image](https://github.com/user-attachments/assets/be40a385-3da4-4bd9-8909-3831a7f21e6d)
![image](https://github.com/user-attachments/assets/c7d2663f-0b79-4f68-9ace-592f990f28a8)

2024-11-19 08:34 UTC, wonderwhy-er commented
We also have many models and providers, probably we need to disable such features when untested provider/model are used

2024-11-19 12:59 UTC, pjmartorell requested changes

2024-11-19 12:59 UTC, pjmartorell commented on app/components/chat/BaseChat.tsx
> +    console.log(provider);
this should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/components/chat/UserMessage.tsx
> +// }
this commented block should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/lib/.server/llm/stream-text.ts
> +  // const modelMatch = message.content.match(MODEL_REGEX);
this comment should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/lib/.server/llm/stream-text.ts
> +  // const providerMatch = message.content.match(PROVIDER_REGEX);
this comment should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/lib/.server/llm/stream-text.ts
> +          text: item.text?.replace(/\[Model:.*?\]\n\n/, '').replace(/\[Provider:.*?\]\n\n/, '')
these regexes are being repeated multiple times, can you use MODEL_REGEX and PROVIDER_REGEX or add them to constants.ts?

2024-11-19 12:59 UTC, pjmartorell commented on app/lib/.server/llm/stream-text.ts
> +
this comment should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/routes/api.chat.ts
> +  // console.log('Request received:', request.url);
these comments should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/routes/api.chat.ts
> +
these comments should be removed

2024-11-19 12:59 UTC, pjmartorell commented on package.json
> +    "lucide-react": "^0.460.0",
this package is not needed and should be removed

2024-11-19 12:59 UTC, pjmartorell commented on pnpm-lock.yaml
> +
it should be removed

2024-11-19 12:59 UTC, pjmartorell commented on app/components/workbench/EditorPanel.tsx
> -                    <React.Fragment key={index}>
what is the reason of removing the index key?

2024-11-19 12:59 UTC, pjmartorell commented on app/components/chat/UserMessage.tsx
> +    : sanitizedContent;
can this be merged/inserted inside `sanitizeUserMessage` function? otherwise you are unnecessarily looping twice over the contents

2024-11-19 13:54 UTC, pjmartorell commented
> We also have many models and providers, probably we need to disable such features when untested provider/model are used

The upload button could be only available for those models with vision capabilities and frozen/disabled for the others. The dynamic LLMs can be fetched from the OpenRouter API and filter those which have `"modality": "text+image->text"`. The ones that are hardcoded can be flagged in the constants.ts

2024-11-19 21:42 UTC, coleam00 commented
@atrokhym Thank you so much for this, I hope we can get it merged in soon! I appreciate your reviews a ton too @pjmartorell, fantastic!

2024-11-20 01:45 UTC, atrokhym commented
@pjmartorell 
thank you for doing my PR review.
i think i incorporated changes you requested. pls take a look
thanks a lot!

2024-11-22 00:54 UTC, coleam00 commented
@atrokhym Thank you! Let me know if you can get around to reviewing again @pjmartorell!

2024-11-22 02:21 UTC, atrokhym commented
> @atrokhym Thank you! Let me know if you can get around to reviewing again @pjmartorell!
@coleam00 -i did run though those issues @pjmartorell noted.
i implemented all of them and ping him to review again. there are few commits after that.
also - should mention - i might missing something about process like who do what, notifications, etc...
so pls correct or point me in right direction.
this is my first git hub public PR :-)

2024-11-24 19:34 UTC, ar3eh commented
When I tried launching, the model selection does not show up

2024-11-25 05:15 UTC, rxyshww commented
This function is really great! May I ask when the merger will take place?

2024-11-27 21:10 UTC, coleam00 commented
@atrokhym  Would you say this is all ready to go? I can review this within the next couple of days too!

2024-11-27 22:49 UTC, atrokhym commented
> @atrokhym Would you say this is all ready to go? I can review this within the next couple of days too!

it was ready for merge couple of days back...but now more conflicts from main branch are coming...so i need to resolve them first...will do ASAP

2024-11-27 23:08 UTC, coleam00 commented
Sounds good, thank you so much @atrokhym! I would love to showcase this for my update video on Sunday!

2024-11-30 01:42 UTC, coleam00 commented
@atrokhym This is looking phenomenal!

There are a lot of merge conflicts with main right now - could you resolve those/rebase your branch on main?

Also I have a couple of suggestions to really make this PR shine:

1. The "X" after you upload an image has a half circle that makes it look like the image is still uploading.
2. Could you include a preview of the image in the chat messages so when you look at the chat history you can see the images that were uploaded?

Thank you for all your work on this!

2024-11-30 03:12 UTC, atrokhym commented
@coleam00 - could you do review, please?

2024-11-30 17:35 UTC, coleam00 commented
Looks good @atrokhym, thank you for fixing the conflicts! Did you get a chance to see my couple of suggestions as well?

2024-11-30 18:38 UTC, atrokhym commented
> Looks good @atrokhym, thank you for fixing the conflicts! Did you get a chance to see my couple of suggestions as well?

yes and i think item-1 looks much better now

![image](https://github.com/user-attachments/assets/00572401-a125-4089-8e52-116e6086369e)

for item-2 - as of now i don't know to do it....i would need to do some research...

2024-12-02 02:09 UTC, Freffles commented
Is it possible to add the ability to paste an image from the clipboard?

2024-12-02 13:10 UTC, Stijnus commented
Hi, 

I have made some changes to the UserMessage.tsx to display the image in the chat conversation.

<img width="1141" alt="Screenshot 2024-12-02 at 13 52 44" src="https://github.com/user-attachments/assets/f8c51b99-469e-4948-81d9-5c2842b8f5e6">

<img width="1426" alt="Screenshot 2024-12-02 at 13 57 35" src="https://github.com/user-attachments/assets/d1f6288c-5b9e-42a4-ac10-c3822abe139b">

**New Code :** 

`
/*
 * @ts-nocheck
 * Preventing TS checks with files presented in the video for a better presentation.
 */
import { MODEL_REGEX, PROVIDER_REGEX } from '~/utils/constants';
import { Markdown } from './Markdown';

interface UserMessageProps {
  content: string | Array<{ type: string; text?: string; image?: string }>;
}

export function UserMessage({ content }: UserMessageProps) {
  if (Array.isArray(content)) {
    const textItem = content.find((item) => item.type === 'text');
    const textContent = sanitizeUserMessage(textItem?.text || '');
    const images = content.filter((item) => item.type === 'image' && item.image);

    return (
      <div className="overflow-hidden pt-[4px]">
        <div className="flex items-start gap-4">
          <div className="flex-1">
            <Markdown limitedMarkdown>{textContent}</Markdown>
          </div>
          {images.length > 0 && (
            <div className="flex-shrink-0 w-[160px]">
              {images.map((item, index) => (
                <div key={index} className="relative">
                  <img
                    src={item.image}
                    alt={`Uploaded image ${index + 1}`}
                    className="w-full h-[160px] rounded-lg object-cover border border-bolt-elements-borderColor"
                  />
                </div>
              ))}
            </div>
          )}
        </div>
      </div>
    );
  }

  const textContent = sanitizeUserMessage(content);

  return (
    <div className="overflow-hidden pt-[4px]">
      <Markdown limitedMarkdown>{textContent}</Markdown>
    </div>
  );
}

function sanitizeUserMessage(content: string) {
  return content.replace(MODEL_REGEX, '').replace(PROVIDER_REGEX, '');
}
`
Br,

Stijn

2024-12-02 13:42 UTC, Stijnus commented
> Is it possible to add the ability to paste an image from the clipboard?

For this option i have changed the code of the BaseChat.tsx : 

`
/*
 * @ts-nocheck
 * Preventing TS checks with files presented in the video for a better presentation.
 */
import type { Message } from 'ai';
import React, { type RefCallback, useEffect, useState } from 'react';
import { ClientOnly } from 'remix-utils/client-only';
import { Menu } from '~/components/sidebar/Menu.client';
import { IconButton } from '~/components/ui/IconButton';
import { Workbench } from '~/components/workbench/Workbench.client';
import { classNames } from '~/utils/classNames';
import { MODEL_LIST, PROVIDER_LIST, initializeModelList } from '~/utils/constants';
import { Messages } from './Messages.client';
import { SendButton } from './SendButton.client';
import { APIKeyManager } from './APIKeyManager';
import Cookies from 'js-cookie';
import * as Tooltip from '@radix-ui/react-tooltip';

import styles from './BaseChat.module.scss';
import type { ProviderInfo } from '~/utils/types';
import { ExportChatButton } from '~/components/chat/chatExportAndImport/ExportChatButton';
import { ImportButtons } from '~/components/chat/chatExportAndImport/ImportButtons';
import { ExamplePrompts } from '~/components/chat/ExamplePrompts';

import FilePreview from './FilePreview';

// @ts-ignore TODO: Introduce proper types
// eslint-disable-next-line @typescript-eslint/no-unused-vars
const ModelSelector = ({ model, setModel, provider, setProvider, modelList, providerList, apiKeys }) => {
  return (
    <div className="mb-2 flex gap-2 flex-col sm:flex-row">
      <select
        value={provider?.name}
        onChange={(e) => {
          setProvider(providerList.find((p: ProviderInfo) => p.name === e.target.value));

          const firstModel = [...modelList].find((m) => m.provider == e.target.value);
          setModel(firstModel ? firstModel.name : '');
        }}
        className="flex-1 p-2 rounded-lg border border-bolt-elements-borderColor bg-bolt-elements-prompt-background text-bolt-elements-textPrimary focus:outline-none focus:ring-2 focus:ring-bolt-elements-focus transition-all"
      >
        {providerList.map((provider: ProviderInfo) => (
          <option key={provider.name} value={provider.name}>
            {provider.name}
          </option>
        ))}
      </select>
      <select
        key={provider?.name}
        value={model}
        onChange={(e) => setModel(e.target.value)}
        className="flex-1 p-2 rounded-lg border border-bolt-elements-borderColor bg-bolt-elements-prompt-background text-bolt-elements-textPrimary focus:outline-none focus:ring-2 focus:ring-bolt-elements-focus transition-all lg:max-w-[70%] "
      >
        {[...modelList]
          .filter((e) => e.provider == provider?.name && e.name)
          .map((modelOption) => (
            <option key={modelOption.name} value={modelOption.name}>
              {modelOption.label}
            </option>
          ))}
      </select>
    </div>
  );
};

const TEXTAREA_MIN_HEIGHT = 76;

interface BaseChatProps {
  textareaRef?: React.RefObject<HTMLTextAreaElement> | undefined;
  messageRef?: RefCallback<HTMLDivElement> | undefined;
  scrollRef?: RefCallback<HTMLDivElement> | undefined;
  showChat?: boolean;
  chatStarted?: boolean;
  isStreaming?: boolean;
  messages?: Message[];
  description?: string;
  enhancingPrompt?: boolean;
  promptEnhanced?: boolean;
  input?: string;
  model?: string;
  setModel?: (model: string) => void;
  provider?: ProviderInfo;
  setProvider?: (provider: ProviderInfo) => void;
  handleStop?: () => void;
  sendMessage?: (event: React.UIEvent, messageInput?: string) => void;
  handleInputChange?: (event: React.ChangeEvent<HTMLTextAreaElement>) => void;
  enhancePrompt?: () => void;
  importChat?: (description: string, messages: Message[]) => Promise<void>;
  exportChat?: () => void;
  uploadedFiles?: File[];
  setUploadedFiles?: (files: File[]) => void;
  imageDataList?: string[];
  setImageDataList?: (dataList: string[]) => void;
}
export const BaseChat = React.forwardRef<HTMLDivElement, BaseChatProps>(
  (
    {
      textareaRef,
      messageRef,
      scrollRef,
      showChat = true,
      chatStarted = false,
      isStreaming = false,
      model,
      setModel,
      provider,
      setProvider,
      input = '',
      enhancingPrompt,
      handleInputChange,
      promptEnhanced,
      enhancePrompt,
      sendMessage,
      handleStop,
      importChat,
      exportChat,
      uploadedFiles = [],
      setUploadedFiles,
      imageDataList = [],
      setImageDataList,
      messages,
    },
    ref,
  ) => {
    const TEXTAREA_MAX_HEIGHT = chatStarted ? 400 : 200;
    const [apiKeys, setApiKeys] = useState<Record<string, string>>({});
    const [modelList, setModelList] = useState(MODEL_LIST);

    useEffect(() => {
      // Load API keys from cookies on component mount
      try {
        const storedApiKeys = Cookies.get('apiKeys');

        if (storedApiKeys) {
          const parsedKeys = JSON.parse(storedApiKeys);

          if (typeof parsedKeys === 'object' && parsedKeys !== null) {
            setApiKeys(parsedKeys);
          }
        }
      } catch (error) {
        console.error('Error loading API keys from cookies:', error);

        // Clear invalid cookie data
        Cookies.remove('apiKeys');
      }

      initializeModelList().then((modelList) => {
        setModelList(modelList);
      });
    }, []);

    const updateApiKey = (provider: string, key: string) => {
      try {
        const updatedApiKeys = { ...apiKeys, [provider]: key };
        setApiKeys(updatedApiKeys);

        // Save updated API keys to cookies with 30 day expiry and secure settings
        Cookies.set('apiKeys', JSON.stringify(updatedApiKeys), {
          expires: 30, // 30 days
          secure: true, // Only send over HTTPS
          sameSite: 'strict', // Protect against CSRF
          path: '/', // Accessible across the site
        });
      } catch (error) {
        console.error('Error saving API keys to cookies:', error);
      }
    };

    const handleFileUpload = () => {
      const input = document.createElement('input');
      input.type = 'file';
      input.accept = 'image/*';

      input.onchange = async (e) => {
        const file = (e.target as HTMLInputElement).files?.[0];

        if (file) {
          const reader = new FileReader();

          reader.onload = (e) => {
            const base64Image = e.target?.result as string;
            setUploadedFiles?.([...uploadedFiles, file]);
            setImageDataList?.([...imageDataList, base64Image]);
          };
          reader.readAsDataURL(file);
        }
      };

      input.click();
    };

    const handlePaste = async (e: React.ClipboardEvent) => {
      const items = e.clipboardData?.items;

      if (!items) {
        return;
      }

      for (const item of items) {
        if (item.type.startsWith('image/')) {
          e.preventDefault();

          const file = item.getAsFile();

          if (file) {
            const reader = new FileReader();

            reader.onload = (e) => {
              const base64Image = e.target?.result as string;
              setUploadedFiles?.([...uploadedFiles, file]);
              setImageDataList?.([...imageDataList, base64Image]);
            };
            reader.readAsDataURL(file);
          }

          break;
        }
      }
    };

    const baseChat = (
      <div
        ref={ref}
        className={classNames(
          styles.BaseChat,
          'relative flex flex-col lg:flex-row h-full w-full overflow-hidden bg-bolt-elements-background-depth-1',
        )}
        data-chat-visible={showChat}
      >
        <ClientOnly>{() => <Menu />}</ClientOnly>
        <div ref={scrollRef} className="flex flex-col lg:flex-row overflow-y-auto w-full h-full">
          <div className={classNames(styles.Chat, 'flex flex-col flex-grow lg:min-w-[var(--chat-min-width)] h-full') [...]

2024-12-02 20:07 UTC, atrokhym commented
@Stijnus  - thank you alot for those 2 improvement! I added them into branch

2024-12-03 20:21 UTC, coleam00 commented
Nice work @atrokhym and @Stijnus, thank you very much!

@atrokhym how are you feeling about this being ready to merge? I see some comments that need to be cleaned up but otherwise it is looking great to me! Tested it again just now.

2024-12-03 21:52 UTC, atrokhym commented
> Nice work @atrokhym and @Stijnus, thank you very much!
> 
> @atrokhym how are you feeling about this being ready to merge? I see some comments that need to be cleaned up but otherwise it is looking great to me! Tested it again just now.

i run through those comments a while ago (resolved them as suggested)
so its ready for merge. no conflicts yet...:-)

2024-12-04 00:11 UTC, Freffles commented
> Nice work @atrokhym and @Stijnus, thank you very much!
> 
> @atrokhym how are you feeling about this being ready to merge? I see some comments that need to be cleaned up but otherwise it is looking great to me! Tested it again just now.

Frickin' awesome job peeps 😁 Thank you!

2024-12-04 16:53 UTC, merged

2024-12-04 17:00 UTC, Stijnus commented
@coleam00 you are welcome ;) but @atrokhym did the most part i just added a few things.. I will continue to add my support to the new pull requests to see if i can contribute to it.

Br,

Stijn

2024-12-04 17:36 UTC, atrokhym commented
cool! thx everybody!

2024-12-05 09:29 UTC, tobalsan commented
Hallelujah! 
Been waiting for this feature the minute I discovered this Bolt fork (which wasn't named OttoDev yet).

Thank you guys for the awesome work.